### ISSUE TITLE
Support for M1 Mac?

### ISSUE THREAD

**Issue by tamanugi** [jnr/jnr-unixsocket#95]
Hi, Thanks for awesome library ✨ 

I  facing issue when use [docker-maven-plugin](https://github.com/fabric8io/docker-maven-plugin).

```
Execution default-cli of goal io.fabric8:docker-maven-plugin:0.38-SNAPSHOT:build failed:
An API incompatibility was encountered while executing io.fabric8:docker-maven-plugin:0.38-SNAPSHOT:build:
 java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
```

https://github.com/fabric8io/docker-maven-plugin/issues/1257#issuecomment-793558336

Questions
- is jnr-unixsocket  support for M1 Mac?
- if not support, any plan support ?

**Comment by headius** [comment]
@tamanugi The M1 bit would largely be within https://github.com/jnr/jffi, which has preliminary support for M1 already. The main thing missing is support for varargs, which requires some native changes to how we set up the argument list (https://github.com/jnr/jffi/issues/105).

So, it may work today, since I don't think we use any varargs calls in jnr-unixsocket!

**Comment by speechkey** [comment]
https://github.com/jnr/jffi/issues/105 looks like to be fixed now

**Comment by tamanugi** [comment]
@speechkey @headius 

latest version docker-maven-plugin works as expected 🎉🎉🎉🎉🎉
Thanks😍
